Vet Clinic Database Setup
DarkxDev/vet-clinic-db pull request #1
Opened 2023-03-27 22:46 UTC by DarkxDev

- Set up new database named `vet_clinic`
- Created a table named animals with columns `id name date_of_birth escape_attempts neutered weight_kg`
- Wrote queries with multiple quests.

2023-03-27 23:11 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @DarkxDev 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 23:11 UTC, tresorsawasawa commented on data.sql
> +INSERT INTO animals (id, name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES (4, 'Devimon', 'May 12, 2017', 5, 1::BIT, 11);
- [ **OPTIONAL** ] Good job adding all the required data. However, I think it would be better if you use the `true` or `false` notation instead of `1::BIT` one on the `column` as this will appear easy and understandable for non technical users.

2023-03-27 23:11 UTC, tresorsawasawa commented on queries.sql
> +SELECT name FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-12-31';
- [ ] Kindly make sure you update the above `query` to correctly answer the asked question as the current one exuledes both animals born on `'2016-01-01'` AND `'2019-12-31';`. For that you can use `>=` and `<=` notation instead of `BETWEEN`. For more information, just refer this **[link](https://stackoverflow.com/questions/1630239/sql-between-vs-and/1630254)**

2023-03-27 23:11 UTC, tresorsawasawa commented on queries.sql
> +SELECT * FROM animals WHERE weight_kg BETWEEN 10.4 AND 17.3;
- [ ] As required for the project, kindly make sure you add  screenshots all queries results to the pull request description. This to help to ensure that you run the queries with success. Good job

---

2023-03-27 23:58 UTC, DarkxDev commented on queries.sql
> +SELECT * FROM animals WHERE weight_kg BETWEEN 10.4 AND 17.3;
![Queries_1](https://user-images.githubusercontent.com/77408085/228092674-91f04d36-4e54-45d5-858f-b693cb9152d7.png)
![Queries_2](https://user-images.githubusercontent.com/77408085/228092677-e80e81ff-cad5-4a6e-a8bb-8387f2efdaa0.png)

2023-03-28 00:04 UTC, DarkxDev commented on queries.sql
> +SELECT name FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-12-31';
Hi @tresorsawasawa the `BETWEEN` operator is inclusive, meaning both delimiting dates are considered in range, therefore, selected, which would be the same as using `>=` and `<=`. These operators are useful when one or both limiting ranges must be excluded. You can find more information about it [here.](https://www.w3schools.com/sql/sql_between.asp)

2023-03-28 00:04 UTC, DarkxDev commented on data.sql
> +INSERT INTO animals (id, name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES (4, 'Devimon', 'May 12, 2017', 5, 1::BIT, 11);
You're right @tresorsawasawa! Recommendation applied, thank you.

2023-03-28 00:19 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @DarkxDev 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 

- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 00:45 UTC, merged